# Generated by Django 4.2.9 on 2024-01-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='Profilepic')),
                ('mobile', models.CharField(max_length=20)),
                ('item_category', models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Desktop Computer', 'Desktop Computer'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Charger', 'Charger'), ('Battery', 'Battery'), ('Cables and Wires', 'Cables and Wires'), ('Other Electronic Devices', 'Other Electronic Devices')], max_length=70)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='Profilepic')),
                ('mobile', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('total_clients', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
